import { StyleSheet } from "react-native";

import { colors } from "./colors";

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.navy },
  content: { padding: 22, paddingBottom: 40 },
  basicScreen: { flex: 1, backgroundColor: colors.navy, padding: 22, paddingTop: 70 },
  header: {
    marginTop: 48,
    marginBottom: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  greeting: { color: colors.cream, fontSize: 30, fontWeight: "800" },
  date: { color: colors.muted, fontSize: 16, marginTop: 6 },
  bell: { fontSize: 26 },
  heroCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 28,
    padding: 24,
    marginBottom: 20,
  },
  label: {
    color: colors.pink,
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.2,
    marginBottom: 10,
  },
  workoutTitle: { color: colors.cream, fontSize: 38, fontWeight: "900", marginBottom: 10 },
  distance: { color: colors.pink, fontSize: 44, fontWeight: "900", marginBottom: 24 },
  muted: { color: colors.muted, fontSize: 14 },
  body: { color: colors.muted, fontSize: 18, lineHeight: 26 },
  infoText: { color: colors.cream, fontSize: 18, fontWeight: "800", marginBottom: 12 },
  primaryButton: {
    backgroundColor: colors.pink,
    padding: 18,
    borderRadius: 18,
    alignItems: "center",
    marginTop: 18,
  },
  primaryButtonText: { color: colors.navy, fontSize: 15, fontWeight: "900", letterSpacing: 0.8 },
  threeColumn: { flexDirection: "row", gap: 12, marginBottom: 20 },
  miniCard: {
    flex: 1,
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 22,
    padding: 16,
  },
  miniValue: { color: colors.cream, fontSize: 24, fontWeight: "900", marginBottom: 8 },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 26,
    padding: 22,
    marginTop: 20,
    marginBottom: 20,
  },
  progressRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 18,
  },
  progressTitle: { color: colors.cream, fontSize: 18, fontWeight: "800" },
  progressPercent: { color: colors.pink, fontSize: 22, fontWeight: "900" },
});
